### ISSUE TITLE
2FA/MFA issue

### ISSUE THREAD

**Issue by DementedCain** [balzack/databag#105]
Enabling multifactor authentication only works in google authenticator, from what I've been able to test. Applications like Authy and Yubico authenticator only return an error when attempting setup. Authy and Yubico are preferable to many people as they add another layer of security to authentication. I'm not entirely aware of what may cause this issue, but I would be very interested in seeing this improvement implemented in the future. 
I love the work you've put in with this service.

**Comment by balzack** [comment]
Thank you for reporting this. I will look into the issue today

**Comment by balzack** [comment]
It seems Authy doesn't support the internal SHA256 algorithm for MFA, even though it seems to accept the QR code. I will update the container to be more flexible in the next day or two. Let me know if you use one of the container services and I will update the container there as well. Thanks again for reporting this issue.

**Comment by balzack** [comment]
The MFA issue should now be resolved in the container tagged "latest". If you get a chance, and you update an confirm? Thanks for your help.

**Comment by balzack** [comment]
Thanks! This project is really fun for me to work on, especially when others find it useful :)
