### ISSUE TITLE
Error when accepting a connect request through application

### ISSUE THREAD

**Issue by lordvic1001** [balzack/databag#107]
When attempting to accept a connect request, an error is displayed on screen. It seems to still work and add the contact via iPhone, but Android doesn't have the same experience. I end up typically adding the user through the web console. Not sure if this is an existing issue, but I didn't see it within the list.

**Comment by balzack** [comment]
Hmm, this is new to me. Is this occurring between on accounts on the same server? Are you using https to communicate with the server with both the mobile and browser app? I will try and reproduce if I can get more details. Sorry for the trouble you are having.

**Comment by lordvic1001** [comment]
These accounts are all on the same server. Fully patched. I am using https with a cert for the connection (LetsEncrypt) via nginx reverse proxy. Submitting the request is fine, but accepting it seems to be the issue.

**Comment by balzack** [comment]
I was just able to reproduce an error in accepting a connection by setting an invalid value in the 'Federated host' field in the admin dashboard. Can you confirm the value you have set in your field? My demo server [https://databag.coredb.org] for example has set 'databag.coredb.org'.

**Comment by lordvic1001** [comment]
![image](https://github.com/balzack/databag/assets/142373171/8928d782-e218-46ff-83ae-714ae4a2c295)
I've confirmed this is proper. SSL cert is valid. The only thing i can think of that would be an issue is that i'm using a cname in DNS to go to my server (dynDNS type setup). Any issues with that or no?

**Comment by balzack** [comment]
I think the cname should work fine. I will investigate further; this is my understanding of the issue so far:
- a contact request can be issued without problem (from iphone, android and browser)
- a contact request cannot be accepted from android, but it does work from iphone and browser

Could you create two accounts on the demo server and see if the error occurs? If it does not, can you create two new accounts on your server and see if the error still persists? 

Thanks again for helping me understand the issue. I'm sure you're not the only one.

**Comment by balzack** [comment]
ack....I do see this issue now. I will fix it and push out an update this week. Thank you for reporting this!

**Comment by balzack** [comment]
I have pushed an update to android and iphone. Can you verify the issue is fixed when you get a chance? The fdroid update will take a little longer to publish, but I don't believe you were using that platform. Thank you for your help in improving this project!

**Comment by lordvic1001** [comment]
I'll test this tonight and possibly this weekend as well.

**Comment by lordvic1001** [comment]
Update: Just wanted to follow-up and let you know this is fully functional.

**Comment by lordvic1001** [comment]
Fixed by Balzack himself.
