### ISSUE TITLE
Cannot login with Android app to self-hosted server when TOTP is enabled

### ISSUE THREAD

**Issue by Sommerwiesel** [balzack/databag#109]
Hello there,
first off, great software.

Now, I've just finished setting it up on my own server, including a valid domain, ssl, coturn with ssl.
I'm pretty confident everything is in order. I can login via browser without any issues (both admin and my user). All accounts use 32 char random passwords (without special chars) and have TOTP enabled.

Login via Andrdoid app, with enabled TOTP, however, doesn't work.

**Normal user:**
weidenwiesel@im.nerdvpn.de

Error on frontend: Error, please try again (translated from German)

Error in docker logs:
```shell
2024/07/01 04:44:36 /internal/api_addAccountApp.go:33 totp code required
2024/07/01 04:44:36 POST /account/apps?appName=Databag&appVersion=1.5&platform=berlin&deviceToken=null&pushType=null AddAccountApp 93.972086ms
``` 

**admin:**
server: im.nerdvpn.de

Error on frontend: Error, please try again (translated from German)

Error in docker logs (I censored the token):
```shell
2024/07/01 04:46:05 GET /admin/status GetNodeStatus 413.393µs
2024/07/01 04:46:05 /internal/api_getNodeConfig.go:12 invalid session token
2024/07/01 04:46:05 GET /admin/config?token=###### GetNodeConfig 721.305µs
``` 

As soon as I disable TOTP, login works.
Disabling TOTP is not an option for me, so can you please look into this?

Thanks :)

**Comment by balzack** [comment]
Very strange...I wonder why Google Play installed the only one. Thank you for figuring this out...and thanks for using this project!
