### ISSUE TITLE
Add and Admin option to enable 'Create Account'?

### ISSUE THREAD

**Issue by bmcgonag** [balzack/databag#11]
I see the option from a private browser window, but it shows a disabled cursor on hover. Can't find a setting to enable it in the UI as an admin.  Is there a way to enable this?

**Comment by balzack** [comment]
From the admin screen, there should be an add user button. This will create a link that you can use for yourself or send to someone to create an account. 

By default public access to creating accounts is disabled. You can enable it in the DB if you aren't worried about random people creating accounts. I can send you some command line instructions if that is what you are wanting.

**Comment by bmcgonag** [comment]
I'll put my suggestion in story form, but I would love to see this as an option in the admin settings that you already have. 

As an administrator of a Databag server, I would like to have a simple toggle switch that allows me to enable the "Create Account" option so users can create their own accounts without needing a specific invite.  

Optionally, it would be nice to be able to list a set of domains for which a prospective user would need to enter as part of their email address in the create account form, as a simple filtering method to limit who signs up.  (e.g. I allow databag.org, opensourceisawesome.com, so any person entering an email address with either of those domains would be allowed, and anyone else would be rejected.

**Comment by balzack** [comment]
The first point is straight forward, and I will add it to the top of my backlog before the tutorials as it will be fairly easy.

The second point is less clear to me. The accounts on a node are not related to email addresses. It's misleading that I use the '@' and has confused other people, so I would like to change it if there is another appropriate character. Say you create an account on your node with dns 'example.com', and you pick an available handle 'me'. Your account referenced in other areas of the app is listed as 'me@example.com'. You can't create 'me@databag.org' on the node with dns name 'example.com'.

**Comment by bmcgonag** [comment]
I understand your point. Let me think about it a bit, and see if I come up with another way for part 2.

**Comment by benjaminbhollon** [comment]
I'd second that making open registration possible through the dashboard would be nice.

**Comment by balzack** [comment]
Here is the command line steps for setting open access until I can add the feature:

sqlite3 /var/lib/databag/databag.db
sqlite>  insert into configs (config_id, bool_value) values ('open_access', true);
sqlite>  insert into configs (config_id, num_value) values ('account_limit', 128);

**Comment by balzack** [comment]
latest container & webapp now have this as a UI options. thx!
