### ISSUE TITLE
WebUI freezes when typing fast 

### ISSUE THREAD

**Issue by zaydogan** [balzack/databag#117]
Hi balzack !

Under certain circumstances, an open topic breaks and freezes the website.
Mostly, when typing fast and sending messages fast (spamming), very often a message appears "operation failed. Please try again". If you press ok and continue, you will probably hit that error again, but every now and then (can't pinpoint exactly when), the browser stops sending messages and completely freezes. If you reload the page and click on that topic, to reopen it, the topic will not load and wait until Chrome tells you to wait or close the page.
You can create a new topic and continue there, but the old topic is broken. It will not load and everytime you click on it, it will freeze the tab. This happens on Chrome and Brave Browser. 
Interestingly it does not happen on Safari. 
I can grant you access to my server, so you can verify and anlalyze it.

**Comment by zaydogan** [comment]
<img width="1440" alt="Bildschirmfoto 2024-10-18 um 13 04 50" src="https://github.com/user-attachments/assets/b6e0537e-97ee-44d3-8016-fb0a959be916">

**Comment by zaydogan** [comment]
I thought, this is network related, but i am not sure. it rather looks like a react problem.
the topics seem to be preloaded when opening the page.
it will preview the last message on left overview.
but when you click on the dead topic, the messages do not appear on the right side (the main window) and it freezes.

**Comment by balzack** [comment]
How easily can you reproduce the issue? I just tried quickly and couldn't. If I can reproduce, I should be able to easily fix it. If the UI hangs, it's likely a bug in my javascript, where it's falling into some busy loop. I'll spend a bit more time trying to reproduce.

Thanks for bringing it to my attention!

**Comment by zaydogan** [comment]
Okay, I can reproduce it now.
It's not the frequency at which you type and send, but the length of the data.
If I open a new topic and send this string:
"hdajshdkjaskjdhakljshdklajghsdkjahsdjklhaskjdhakjlshdlakjshdklajhsdlkajshdlakjshdlkajshda"
the topic immediately freezes. You don't need to type it. Copy and paste is fine.

**Comment by zaydogan** [comment]
If i put spaces into the string above it works. 
so maybe it's a regex that cannot parse long strings ?
<img width="931" alt="Bildschirmfoto 2024-10-19 um 17 00 18" src="https://github.com/user-attachments/assets/16135184-0bd6-4aca-93b6-84b9888a12b6">

**Comment by zaydogan** [comment]
With strings longer than 30 chars the time for every new char you add, doubles the time.
30 chars take about 2 seconds.
31 chars take about 3 seconds.
32 chars take about 6 seconds.
33 chars take about 12 seconds.
34 chars take about 22 seconds.
>= 35 chars take infinite amout of time.

**Comment by balzack** [comment]
You are awesome, thank you!

I am able to reproduce the issue. For some reason the RegEx I use to identify if a portion of the message should be clickable struggles with longer strings. I will fix it today, and push out a server update with the fix over the next week. 

Thanks again for you help with this project

**Comment by balzack** [comment]
Does this issue appear fixed in the latest webapp.tar.gz build as well?

**Comment by zaydogan** [comment]
no, it's fixed.
but it still happens on the mobile app.

**Comment by zaydogan** [comment]
as in, if you type a long string on web it won't show up in the app and the app will crash. 
and it won't load if there is a long string anywhere in the topic history.

**Comment by zaydogan** [comment]
i am on ios (iphone)

**Comment by balzack** [comment]
Okay, I will push out an IOS update this week. Thanks.

**Comment by balzack** [comment]
When you get a chance, can you updated the IOS app and see if the long string is still and issue?
thank you!

**Comment by zaydogan** [comment]
Hi ! I've been waiting for the update :D
The issue is now fixed.
Thanks a lot !

**Comment by balzack** [comment]
awesome!!  thank you
