### ISSUE TITLE
input text loses formatting (whitespace) on WebUI

### ISSUE THREAD

**Issue by zaydogan** [balzack/databag#119]
if you copy and paste text, for example code, it will lose the formatting.
for example, if you copy & paste the code below:

```
//GetAccountApps TODO list apps attached to account
func GetAccountApps(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
```

it will look like this on the output:

//GetAccountApps TODO list apps attached to account
func GetAccountApps(w http.ResponseWriter, r *http.Request) {
w.Header().Set("Content-Type", "application/json; charset=UTF-8")
w.WriteHeader(http.StatusOK)
}

But if you edit the message, the formatting is still retained.
This looks like output formatting, where the whitespace is removed.

Okay. To be fair. The formatting is also lost here on github, unless the text is enclosed in a code tag.

this only happens on web, on the mobile app, the formatting is retained.

**Comment by balzack** [comment]
Thank you for spotting this! I needed to fix the css on displayed message.

I update the release artifact with the fix:
https://github.com/balzack/databag/releases/download/v1.1.1021/webapp.tar.gz

The release asset is repackaged from the latest build artifact:
https://github.com/balzack/databag/actions/runs/11447757544

**Comment by zaydogan** [comment]
Thank you ! It works !

**Comment by zaydogan** [comment]
It works!

**Comment by balzack** [comment]
thanks for your help :)
