### ISSUE TITLE
Easily start a direct message with another user.

### ISSUE THREAD

**Issue by bmcgonag** [balzack/databag#12]
As a user I would like to easily begin a direct message with another user instead of creating a special topic just for that user.

Suggested workflow:
1. Show a persistent button (icon) on the right end of the users list (left of the other icons) that would start a DM.  This works best for both mobile and desktop.

![DM-for Databag](https://user-images.githubusercontent.com/7346620/225302494-bf0fc8ef-d4b7-4ca0-9f7f-42271dc6f6df.png)

**Comment by balzack** [comment]
Once the DM thread is started, is it viewable in the main topic list, or is it a special type of communication that is reachable only through the contact list?

**Comment by bmcgonag** [comment]
Great question. Yes, I would think it would just start a new topic between those two people, alleviating the need to click New Topic, call it a DM, then pick the person.  Just automate the process. Does that make sense?

**Comment by balzack** [comment]
So to paraphrase, is it basically a shortcut, but with some extra implications?

1) If you click on it and there is no previous 'DM' topic with that contact, it creates a new topic with that contact as member, and navigates to the new topic thread

2) If you click on it and there IS a previous 'DM' topic with that contact, it navigates to that existing 'DM' topic thread

Q] Should 'DM' topics be editable? Can you change the subject name or add/remove members?

**Comment by balzack** [comment]
Sounds good. Currently you can edit the topic subjects as well as change their membership, so i'll leave that enabled.

**Comment by balzack** [comment]
<img width="453" alt="Screen Shot 2023-04-16 at 10 10 54 PM" src="https://user-images.githubusercontent.com/96387156/232384903-e5fe2b8d-10b6-4baf-a2c7-eeda8899a110.png">

I bundled this feature with the release of audio and video calling. It will still be available even if calling is not enabled, it is just accessible from the same point as the screenshot indicates.

When the user clicks on the 'DM' button, a new DM thread will be created if one doesn't already exist. If one does exist, it will open up the existing thread. A 'DM' thead is defined as a hosted topic with only the one recipient and a default title.

Let me know if this meets your expectations of the feature. Thanks for the request!

**Comment by bmcgonag** [comment]
Sorry, took me a few days to get back to it, but this is awesome!  Just updated, and tried it and it works great!
