### ISSUE TITLE
Clickable URLs in messages

### ISSUE THREAD

**Issue by mimnix** [balzack/databag#17]
Hello @balzack , thank you very much for this awesome project!
I would like to submit the request to have the URLs clickable/tappable within the conversation messages. At the moment users neither can select text to copy-paste links nor click them as hyperlink. Thanks again!

**Comment by balzack** [comment]
Thank you for the suggestion; that's a very good point. It should be easy to add, so I will add it just after I finish the feature I am currently working. Probably a month out. Thank you for the interest in the project!

**Comment by balzack** [comment]
Several people were interested in this feature, so I made a quick small release to support this. In the topic thread, you should be able to click on a link, and it will open in a new tab. Can you let me know if it works the way you would expect?

You can test it out on the demo site 'databag.coredb.org' or by updating your server. The mobile apps have also been updated, but the ios version is still going through the validation process.

**Comment by mimnix** [comment]
> Several people were interested in this feature, so I made a quick small release to support this. In the topic thread, you should be able to click on a link, and it will open in a new tab. Can you let me know if it works the way you would expect?
> 
> You can test it out on the demo site 'databag.coredb.org' or by updating your server. The mobile apps have also been updated, but the ios version is still going through the validation process. 

Dear @balzack
I've just tested the update on my own databag instance and on the android client: both of them work like a charm!! Thank you very much for this fix you have provided!

**Comment by balzack** [comment]
Awesome! thanks for helping me improve this project.

**Comment by daedric7** [comment]
Did a quick test:

![image](https://user-images.githubusercontent.com/4562461/229922227-f06dece8-0667-4d5f-ace8-740a00547e0c.png)

Web: All urls work as intended and are detected by the webapp as such.

Android: https://www.google.pt worked, www.sapo.pt is detected as a url (italic) but touching it does nothing, same as slashdot.org.

**Comment by balzack** [comment]
Interesting...thank you. I think means my pattern matcher is identifying it as a URL, but the library 'braintree/sanitize-url' which protects against XSS is refusing it.  I should be able to get this working. Thanks again...

**Comment by daedric7** [comment]
> Interesting...thank you. I think means my pattern matcher is identifying it as a URL, but the library 'braintree/sanitize-url' which protects against XSS is refusing it. I should be able to get this working. Thanks again...

Now that you mention... i don't think it really needs fixing.

Is a URL a URL if it does not have http:// https:// ftp:// irc:// before it ? should nnnnnnn.xxx be considered a URL ?

To be honest, it's fine as it is. Perhaps not detect as URL would be enough :)

Thank you a lot !

**Comment by mimnix** [comment]
> > Interesting...thank you. I think means my pattern matcher is identifying it as a URL, but the library 'braintree/sanitize-url' which protects against XSS is refusing it. I should be able to get this working. Thanks again...
> 
> Now that you mention... i don't think it really needs fixing.
> 
> Is a URL a URL if it does not have http:// https:// ftp:// irc:// before it ? should nnnnnnn.xxx be considered a URL ?
> 
> To be honest, it's fine as it is. Perhaps not detect as URL would be enough :)
> 
> Thank you a lot !

I agree. I think that the detection of the URL in form of "scheme + fully qualified domain name" is really enough.
