### ISSUE TITLE
Is robots.txt on a sensible default setting?

### ISSUE THREAD

**Issue by hughbris** [balzack/databag#28]
I checked the [`robots.txt` file that this web app serves](https://github.com/balzack/databag/blame/e406ab4c766fe55403c65ef262312c2897461456/net/web/public/robots.txt#L3) out of the box. It shows a blank value for `Disallow:` which I must admit I've never seen. From limited research, that seems to advise crawlers to index anything they can find (which is going to only be a login page...).

I wonder if that's the best default. It's not the one I want for my public installation anyway and I'm glad I checked.

Ideally, there would be a documented and simple way to change this. The `Dockerfile` could support an environment variable to toggle it between a restrictive default and a sensible permissive one. I'm happy to provide a PR when I have time if you agree.

I was able to change mine in the docker-compose to easily override the build's default:

```yaml
volumes:
     - <my/host/directory>/robots.txt:/app/databag/net/web/build/robots.txt:ro
```

Perhaps at a minimum, this could be documented.

**Edit:** The docker-compose host `robots.txt` file referenced above _should be created before_ you try this, else docker will create an empty host _directory_ called `robots.txt/` and then fail!

**Comment by balzack** [comment]
Thanks for catching this! it should be set to "/" right? I doubt anyone wants a crawler or bot on their instance.
I can update the code, but if you want to do a PR, that's great to.

**Comment by hughbris** [comment]
Yep, '/' is the better value. It's not security of course, but it removes the vector of search engine discovery, in case a vulnerability is found.

Thanks for the fast response, would like to do a PR soon.

**Comment by balzack** [comment]
Sounds good. In my opinion it doesn't need to be configurable, we can just update the robot.txt file. I am open to suggestions if you disagree. I await your PR, no rush.

**Comment by hughbris** [comment]
> Sounds good. In my opinion it doesn't need to be configurable, we can just update the robot.txt file. I am open to suggestions if you disagree. I await your PR, no rush.

I did think we could do more, hence my delay, but realised overnight that there is no need. And my workaround doesn't even really need documenting since it's basic Docker stuff.

Cheers

**Comment by balzack** [comment]
It might be something to add in the future as the project matures. For now I'm leaning towards keeping things as simple as possible. I merged your PR and will build a new docker image tonight. Thanks again!
