### ISSUE TITLE
Add to FOSS app store(s), f-droid etc.

### ISSUE THREAD

**Issue by hughbris** [balzack/databag#30]
I would love to try the Android app but do not have Google Play/Store/whatever on my phone, only [f-droid](https://f-droid.org/). I don't particularly feel like working out how to build it either. (Well, I have had traumatic experiences in the past...)

Would you consider submitting a [request for packaging to f-droid](https://gitlab.com/fdroid/rfp)? Having it there might expose databag to some new users, too. Anyone can submit these, but I suspect you'll do the most complete job.

Cheers

**Comment by balzack** [comment]
I am pretty close to getting a build through fdroid. Someone was helping me, and we have it building on their local server. To be able to submit I need to be able to generate the builds myself, and the gitlab pipeline keeps running out of space. I think I should be able to get it working now that I moved away from expo, but I need to dedicate some time. Hopefully in the next month or two.

Here is the thread for reference: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12183#note_1193758576

**Comment by hughbris** [comment]
Oh weird, sorry I thought I had searched as per their instructions :)

**Comment by balzack** [comment]
I can always post the .apk if anyone wants. It's obviously not advisable to install an apk outside of a store, where it would get reviewed.

**Comment by balzack** [comment]
I need to update the description, but Databag is now live on fdroid (https://f-droid.org/en/packages/com.databag/)
