### ISSUE TITLE
Password characters

### ISSUE THREAD

**Issue by hughbris** [balzack/databag#31]
I am see this error when I try to create accounts using a Create Account Link and use a complex password (it seems):

![Error dialog: "Create Account Error: Please check with you administrator."](https://user-images.githubusercontent.com/288202/235826718-c5023281-6848-4624-ad76-5cb4faccb3c9.png)

When I installed my _test_ installation, I used much simpler passwords and did _not_ have this problem.

When I set up my production install accounts, I was able to work around this and successfully create accounts by removing most of the special characters from the password.

I guess there's no harm (and good diagnostic info) in revealing that one of the passwords that would _not_ work was: `s9m/4Tu:sL@_nFf-`. It was generated with a password manager. There was another that failed but unfortunately I don't have that any more.

A couple of weird things I noticed:

* the admin account I set up initially has a few of what I assume are similar problem characters
* as Admin, I can see the "failed" accounts in the list of users, even though they can't log in (I tried that too)

I think you should be able to reproduce this easily. Just ask if you want more info :)

**Comment by hughbris** [comment]
Heh, I just noticed a typo in that popup dialogue too: "you administrator" → "your administrator".

**Comment by balzack** [comment]
Hmm, the fix should be quick. I am wrapping up a feature in the next couple days, and then I'll address this. Thanks for catching this!

**Comment by balzack** [comment]
This should be fixed in the latest container. When you have time, could you verify the fix?

With the 'failed' accounts, the password was saved incorrectly. Those accounts can be accessed from the admin panel with the 'lock' icon, and then the password can be reset (correctly this time), or they can just be deleted.

Thanks for your help with this project.
