### ISSUE TITLE
Copy / Paste image

### ISSUE THREAD

**Issue by ZedSphere** [balzack/databag#43]
Whilst there is a button to upload an image when sending a message, a useful feature i use many times is copy/paste an image into the chat window text field.

This feature can be found on many apps such as whatsapp, facebook messenger and telegram. 

This would enhance the overall user experience.

![image](https://github.com/balzack/databag/assets/119502455/ba597e30-136a-4e80-bcee-772b0432dc02)

**Comment by balzack** [comment]
Is this 'share sheet' integration? For example from another app (like your sceenshot) you can click the share button, and then select 'Databag'. You then get prompted for the topic within which to send the shared item. 

I see it works from the mobile browser and the photo gallery, but testing now I see iMessage isn't sharing properly.

**Comment by balzack** [comment]
I just tested on iOS & whatsapp. From whatsapp, you can tap share on an image, then select databag, and it will paste into the selected topic. I'm not sure if this is the functionality you're looking for.

**Comment by balzack** [comment]
I also just testing on android. From whatsapp, you can tap share on an image, then select databag, and it will paste into the selected topic. Let me know if you where hoping for something else.

**Comment by ZedSphere** [comment]
Hi there, thanks for the feedback. no the function im specifically looking for is this:

scenario 1: search for an image on google - from phone or computer select "copy image" and then paste it into a Databag chat window.

**Comment by balzack** [comment]
Hello, when you get a chance can you update the container and see if the browser functionality is what you expect. I haven't yet updated the mobile apps. Thanks for your help with this project!

**Comment by ZedSphere** [comment]
Thanks for implementing this. works just as expected!

**Comment by ZedSphere** [comment]
implemented and working
