### ISSUE TITLE
F-droid repo

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#44]
I've just cross throw the f-droid repo build comments, if it isn't possible yet to add it to f-droid store repo (they're rigorous) make your own until then

https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/ (Updated)

you can omit the sudo add-apt-repository ppa:guardianproject/ppa 

Cheers !

![168503672-0ce0c740-aa5a-48fa-ad99-7ab34d296ed9](https://github.com/balzack/databag/assets/46766062/a5a6099e-e886-4025-8e05-fddc94d9c3aa)

**Comment by balzack** [comment]
Hmm, interesting. Thanks, seems easy enough to setup.
