### ISSUE TITLE
what is the data flow of this app?

### ISSUE THREAD

**Issue by hasakilol** [balzack/databag#47]
Say user A and user B are in a chat room(topic), A send a message 'Hello'. Does this message go through network directly to B or it goes first to some server(owned by databag or anyone, but not me), then to B?

**Comment by balzack** [comment]
Thanks for the question; the data does not flow through any Databag server.

Scenario: User A creates a topic and adds User B as a member, then User A sends a message.
- User A's node will host the topic
- When User A posts a message, it is sent only to User A's node
- User B's node is then notified of a new message by User A's node (could be the same node)
- User B's app receives the notification through a websocket connection to User B's node
- User B's app pulls the message from User A's node

**Comment by hasakilol** [comment]
A's node and B's node each has their corresponding domain, right?

**Comment by balzack** [comment]
Yes correct. The project supports federation, so accounts on different nodes (and different domains) can communicate.

**Comment by hasakilol** [comment]
Thanks. You can close this thread.
