### ISSUE TITLE
Remove license from FOSS version

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#50]
F-droid app seems to still have a dependency from google store can you confirm that?

![Screenshot_20230719-010056_RwqPBYBlGDrUYB](https://github.com/balzack/databag/assets/46766062/d4271316-28ab-4af6-be35-c8f562a85962)
![Screenshot_20230719-010555_RwqPBYBlGDrUYB](https://github.com/balzack/databag/assets/46766062/f2c5692e-16cc-4aff-9210-044ad569889e)

Thanks !

**Comment by balzack** [comment]
I'm not sure where the license is getting pulled in from. I'll have to look at other f-droid projects and see how they remove it. Thanks for spotting this.

**Comment by balzack** [comment]
If you get a chance, can you verify whether LP still detects a license in the latest f-droid build (500X)?

**Comment by samuraikid0** [comment]
Alright the license is no longer flagged 

Thanks !
