### ISSUE TITLE
Possible grammatical error

### ISSUE THREAD

**Issue by dillfrescott** [balzack/databag#51]
https://github.com/balzack/databag/blob/91f0b0d3ac72c8c4c3add96712a63dbe15a9b36d/app/mobile/src/access/create/Create.jsx#L79

Shouldn't it be `otherwise` instead of `othersize`?

**Comment by balzack** [comment]
yes...thank you! Would you like to make a pull request, or should make the change (up to you)?

Thanks for your help!

**Comment by dillfrescott** [comment]
Ill leave it to you! Im terrible at github lately lol

**Comment by balzack** [comment]
should be fixed now. thx!
