### ISSUE TITLE
[Android] [Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [balzack/databag#54]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by balzack** [comment]
Thank you for pointing this out; I hope to support this soon.

**Comment by balzack** [comment]
I added themed icon support. When you get a chance can you update the mobile app is see if it is what you expect?

Thanks for helping to improve this project!

**Comment by sebastien46** [comment]
That's exactly the implementation I was looking for! Thank you very much and have a nice day.
