### ISSUE TITLE
Bump future versions on F-Droid

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#58]
I think you can now bump the 1.0 version on future releases of databag and probably delete the older ones leaving the last one since a lot of things got fixed since 1 f-droid release.

**Comment by balzack** [comment]
Good suggestion. I deleted the oldest releases and next fdroid release wil tag as 1.1.

**Comment by balzack** [comment]
Thanks for reminding me, I forgot about this. I just published a release for 1.1 with some minor translation fixes. 

Do you find the updated UI to be an improvement? Is the translation useful and/or correct?
