### ISSUE TITLE
Can't copy or open some links

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#59]
I'm unable to copy links or open them

can you check it out ? 
Thanks !

**Comment by balzack** [comment]
Is this in f-droid?

**Comment by samuraikid0** [comment]
Yes, I notice today only

**Comment by balzack** [comment]
Can you give me an example link that doesn’t work? Does adding ‘https://‘
to the front make it work?

**Comment by samuraikid0** [comment]
![Databag](https://github.com/balzack/databag/assets/46766062/696fd5bd-702e-4d75-b1d8-7827de672553)

**Comment by samuraikid0** [comment]
I think its because the end of the url 
Ive tried with https://youtube.com and it opens the browser

**Comment by balzack** [comment]
I run all URLs through sanitize-url to prevent XSS. I could be wrong, but I think because the mobile app opens the browser to a specified URL, all URLs should be sanitized. There must be some character in the URL that are flagged by santiize preventing the link.

**Comment by balzack** [comment]
If you feel sanitize-url is too restrictive, let me know, and I will investigate other options.

**Comment by samuraikid0** [comment]
I'll be trying  with different websites to see if is too common and let you know 

Thanks !

**Comment by samuraikid0** [comment]
Deleting the "#" part of url fixed the link so it's good like it is
 it's not happening commonly

Thanks !
