### ISSUE TITLE
Messages disappear within federated conversations

### ISSUE THREAD

**Issue by lordvic1001** [balzack/databag#60]
When messaging within a conversation with a non-local peer, sometimes images or text messages will no longer be within the senders view. The messages will sometimes show within preview on the main topics page, but will not be present within the conversation body. My non-local peer also had the same issue with a conversation hosted on my server, but I had the full conversation. I haven't checked to see if this occurs within users on the same server, but i'd wager it doesn't.

**Comment by balzack** [comment]
Could you give me a bit more detail about the issue?
- is this happening only with sealed topics or unsealed topics?
- is this happening on mobile or browser, or both? will the same message be missing from both?
- does this happen to all messages within a topic or just a random individual message?
- does restarting the app cause the message to reappear?

Thanks for reporting this, this is obviously a serious issue that I need to resolve. There was a bug recently in the mobile app on some devices where unsealed topic messages would not show up, but that was resolved ~1month ago.

**Comment by balzack** [comment]
Thank you so much for reporting this!!!! This was a serious issue.

I see the problem and will fix it tonight. It will however take around a week for the apps to be deployed through the app stores.

**Comment by lordvic1001** [comment]
Pierre,

This is in the mobile app. It looks like the messages are in the mobile app. Admittedly, i am using a slightly older version and need to update. I'm only really messaging one other remote user. I'll update and attempt to replicate this. Also, restarting the app does not cause the message to re-appear.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by balzack** [comment]
Yes, thank you. I was able to reproduce the issue and fix it for any new messages coming in,

The iOS app has been updated, the fdroid app will be updated in the next few days.

The messages before the fix will still appear missing, but can be recovered by scrolling to the top of the thread and back down.

**Comment by balzack** [comment]
The fdroid app has now also been updated. If you get a chance, can you see if messages continue to disappear?

**Comment by lordvic1001** [comment]
I'm upgrading my server later today, and am using the app store version, but I will test.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by balzack** [comment]
The app store version was updated as well. Thanks!

**Comment by balzack** [comment]
I believe this bug has been fixed....thanks again for reporting it.

**Comment by lordvic1001** [comment]
I can confirm this is resolved.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
