### ISSUE TITLE
Can't login with Android app

### ISSUE THREAD

**Issue by blacksocket** [balzack/databag#64]
Hello All,

I ma trying to login via android app available in google play and still getting "login failed". I am providing login with convention usernam@server.domain and password created previously which working when login via web browser. Anyone help with this issue ?
Thank you!

![image](https://github.com/balzack/databag/assets/13651344/706188e4-5f9d-45ba-abcf-d33c7d8dbb66)

**Comment by balzack** [comment]
Perhaps there is a special character in your password that is not being handled correctly. Can you log in with your browser, and change the password to something 'weak' just to validate? If it does end up being a character causing the issue please let me know what it is.

Thank you for reporting this!

**Comment by blacksocket** [comment]
Hello,

Finally I was able to solve the issue which was related to certificate and SSL conection. Now it works fine.. ;-)

Thenk you for your help!

**Comment by balzack** [comment]
great you have it working. thanks for using this project!
