### ISSUE TITLE
[Request] Dark mode setting

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#72]
Since privacy configured browsers will block the auto dark mode, I'm asking for a setting to enable it 

Thanks ! All the best !

**Comment by balzack** [comment]
Interesting, I did not know about that restriction. I will start a refactor of the browser app soon, which will include multi-language support and dark mode. I will be sure to a setting to manually enable it. Thank you!

**Comment by balzack** [comment]
This should be working on both mobile and browser. Please let me know if there are any issues with it.
