### ISSUE TITLE
How sacalable is SQLite?

### ISSUE THREAD

**Issue by aquaspy** [balzack/databag#74]
Hi,

Sorry about opening a issue that is not really a issue. It looks like you're using SQLite correct? I've just deployed a new server and I'm loving databag. The only issue that I'm thinking about is: Is Databag scalable if I make my server public? Or it is intended to be used more for small communities/family? 

Also, do you accept donations by any means? I would love do donate to this project!

**Comment by balzack** [comment]
Hi, until now an individual server has been designed for smaller groups (communities/family). The server however uses gorm.io, which should make it easy to swap out to a more powerful database when the project gets to that point. Through federation the network should scale well, but this would be through many nodes vs a single powerful node.

Currently I'm not looking for any donations, but am really hoping for feedback and feature requests. I'm really grateful to read you like the project and are using it. Thank you so for your support!
