### ISSUE TITLE
When typing, the text field is not focused after you send the message

### ISSUE THREAD

**Issue by aquaspy** [balzack/databag#75]
Hi there,

This glitch seems to be a bit annoying for most people using Databag on a web browser (desktop).

When you are typing, after you use "enter" to send the message, you need to click on the text field again to type. Here is a video showing the issue:
https://github.com/balzack/databag/assets/49214136/19c71913-164c-425c-8930-6e40cf5fc106

**Comment by balzack** [comment]
Hello....great point, I can see that being annoying. I will include a fix for this in the next server release. 

Awesome feedback, thank you!

**Comment by balzack** [comment]
This should be resolved in the latest docker image 0.1.9. Let me know if you use a specific docker management system that I should push an update to. Thanks for using the project!
