### ISSUE TITLE
Login Android non federated server

### ISSUE THREAD

**Issue by MaximosPr** [balzack/databag#77]
Hi, thanks for that cool app. I want to self-host it in my casaos, but I can't figure out how to login in the Android app with the account I created on the browser. I just want it to work in my home network (+vpn) so I haven't made any proxy configurations and stuff like that. Soory if that question is bothersome I'm a complete beginner in selfhosting.

**Comment by balzack** [comment]
All questions are valuable, so I can learn where the project is lacking.

It sounds like you are trying to use the mobile app with a setup that doesn't support https yet, but that is currently required for the mobile app to work. I am getting a fair amount of requests to have the mobile work with http and just the local IP address, so I will try to support this in the near future. Let me know if I misunderstood your setup.

fwiw: there are a bunch of free services that would allow you to support https, duckdns & letsencrypt

**Comment by MaximosPr** [comment]
So you suggest I point to my local network through duckdns like Https://mydomain.duckdns.org:7000? I could try that I just haven't figured out yet how to do that https thing. But yes that's my setup thanks! (You could also improve the documentation at some point, for the client side mostly)

**Comment by balzack** [comment]
My suggestion (although there are many ways to do this):

- (If on a home network, I think your router needs to port forward ports 80 & 443 to casaos)
- obtain a subdomain with duckdns, or hopto, or any other free service, which would point to your public IP
- In casaos install the 'Nginx Proxy Manager' app.
- In nginx add a proxy host
  - in details tab, enter '<subdomain>.<dns_service>.org' forwarding to your container on port 7000
  - in details tab, enable websocket support
  - in ssl tab, select 'request new ssl certificate
  - in ssl tab, select force ssl
  - save proxy host
- if all works https://<subdoimain>.<dns_service>.org should bring you to your databag instance, which would also be accessible with the mobile app.

**Comment by MaximosPr** [comment]
Thanks a lot mate! I'll try it. Have a great one!

**Comment by MaximosPr** [comment]
It might be a bit out of scope here..but if I have port forwarded for a VPN service do I need to port forward for nginx as well?

**Comment by balzack** [comment]
I'm not sure how your VPN is setup, but it should be possible. I think your right, with a VPN you shouldnt need to port forward on your router.

I assume your VPN provides you with a public facing IP, which is should be what is assigned to your DNS subdomain.

Network traffic destined to that public IP for ports 443 & 80 need to be routed to your casaOS system, which will then reach the listening nginx app.

**Comment by bmpang** [comment]
fwiw I +1 the request to allow the app to work over http. The niche usecase for me is hosting it exclusively on the local network as a way for family to communicate within the house when not physically near each other if internet access is lost while power is still on. Acquiring a domain and setting up something like nginx reverse proxy when we want the app to be only accessible locally would be much less preferable than allowing the app to connect only when our phones are on the home wifi.

**Comment by balzack** [comment]
I've had quite a few requests for this feature now, so I have bumped it's priority. It won't be in the next release as I am mostly focusing on the browser app, but I will include it in the following. Thanks for your interest in the project!
