### ISSUE TITLE
Can't send video/picture with more than 1MB size

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#8]
I'm able to send and receive if the size is lower than 1MB otherwise it isn't send 
- Docker version 0.1.2

Any idea ?

**Comment by balzack** [comment]
I had a similar issue with my reverse proxy. If you are using nginx proxy manager, try the settings:
client_max_body_size 0;
proxy_max_temp_file_size 0;

If you don't think it's a reverse proxy issue, can you tell me a bit more about your setup?

**Comment by samuraikid0** [comment]
> 

Problem solved

Hope in the future be able to customize it 
Thanks & keep the food job

**Comment by samuraikid0** [comment]
*good

**Comment by balzack** [comment]
awesome! if you have any other issues or features you would like, please let me know.
