### ISSUE TITLE
Audio and Video Calling

### ISSUE THREAD

**Issue by CoreyCCarter** [balzack/databag#83]
This isn't much an 'issue' as it is a general question but I am a little confused.  The app supports audio and video calls but I do not see anywhere in the app where to do this. I want to test it out with the demo provided but I don't see any buttons to start any calls in the app.

**Comment by balzack** [comment]
Once you have a contact connected, you should see a call icon in the contact list if your server has setup a STUN/TURN server.

The account from the demo server has the STUN/TURN server configured, so from that contact list, you should be able to call any connected contact.

Let me know if that makes sense, I'm still working on a user guide which would be helpful right about now....

**Comment by CoreyCCarter** [comment]
Makes sense! Thanks so much. I've been meaning to check this app out for weeks and had some free time today to get it up and running! So far it's great!

**Comment by balzack** [comment]
Awesome, please let me know of any issues or features you would like. Thanks again!
