### ISSUE TITLE
The mobile application cannot connect to the server after push notification (wake up).

### ISSUE THREAD

**Issue by metaip** [balzack/databag#91]
Successfully installed the server.

Successfully connected two clients - mobile and browser.
Clients exchanged messages successfully.

The mobile application falls asleep, the browser sends it a message, the application receives a push notification and cannot connect to the server.
Server shows message:
`2024/04/23 03:26:59 http: TLS handshake error from ##.##.##.##:46344: remote error: tls: unknown certificate`

I make a logoff in the mobile application, relogin to the server and everything is fine. 
And everything repeats itself again.
Could you help me please.

Mobile ver - 1.5.
Go version - go version go1.22.2 linux/amd64.
Certificate from letsencrypt.

**Comment by balzack** [comment]
I just tried this with my setup and am not seeing the error. How do you know the app cannot connect to the server? Are you seeing the disconnected icon on the client, and the messages are not syncing?

For the server to show that message, it suggests the outbound communication from that server is failing. This could be either the push notification message or the contact notification message. Can you tell me more about your setup? Are you using unified push? Is the contact generating the push event on the same node? Did you set a DNS name in the admin config for 'federated host'?

Thanks for trying out this project, sorry for the difficulties at the moment.

**Comment by metaip** [comment]
Hello.

Sorry, my mistake.
The file with cert (-c key) had to include the certificate and all root certificates. I only had one registered.
After adding the root certificates everything worked successfully.

Thanks.
