### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [balzack/databag#98]
Firebase is non-free. Is it used for Android?

**Comment by balzack** [comment]
I use it only in the android build, I must have made an error in my merge of common features. I will look now

**Comment by balzack** [comment]
@linui, i think i accidentally tagged my android branch in the release instead of the fdroid branch.

I am sorry for the trouble, the latest release now is tagged from the fdroid branch.

**Comment by licaon-kter** [comment]
@balzack I'm testing https://github.com/balzack/databag/releases/tag/V1.1.13b now

but not sure how to proceed with autoupdates as this Tag versionCode is waaaay higher and checkupdate will just say there's no newer one https://github.com/balzack/databag/blob/v1.1.13/app/mobile/android/app/build.gradle#L107

eg. maybe tag the fdroid versions differently `-fdroid` or  next version bring fdroid versioncode at the same value?

**Comment by balzack** [comment]
Could I increment the minor number to resolve this? (1.2)

With android I use the version code as a build number, which is why they are so different.

**Comment by balzack** [comment]
I guess it would actually have to be (1.6) if that solution seems appropriate.

**Comment by licaon-kter** [comment]
> Could I increment the minor number to resolve this? (1.2)

it's not about versionName, that can be anything even `foobar`

> With android I use the version code as a build number, which is why they are so different.

Android cares about versionCode and so is F-Droid

**Comment by licaon-kter** [comment]
updated recipe but disabled autoupdates for now, until we can pickup the right version

https://gitlab.com/fdroid/fdroiddata/-/commit/92e7116da4798ade518ee0b2d49a0d272462007b

**Comment by balzack** [comment]
I am happy to bump the version code way higher to match android, if that is what you recommend. 

For some (wrong) reason, I thought a large versionCode should be avoided, ie. "Version 1.1 (1081004)"

Thanks again for your support, I'm sorry for the trouble.

**Comment by balzack** [comment]
I see the pipeline build failed, but it seems related to downloading the ndk, and the build works locally. Please let me know if there is something for me to resolve.

**Comment by licaon-kter** [comment]
no, https://gitlab.com/fdroid/fdroiddata/-/jobs/6844374274/artifacts/browse/tmp/ means 3 arches were built, it's just the CI having it's storage filled :)

**Comment by balzack** [comment]
The versionCode has been updated to 1019 in the next release to resolve my previous error. Can auto-updates be re-enabled?

**Comment by licaon-kter** [comment]
Ok, so thee new versionCodes will be 1019001..1019004, yes?

**Comment by balzack** [comment]
yes, I think that is correct. The value in the build.gradle files is 1019, which will produce 1019001..1019004.
thank you!

**Comment by licaon-kter** [comment]
nice https://gitlab.com/fdroid/fdroiddata/-/commit/9b18dd7601237ba67fa9b01dc918cfd56e0d0cb1

**Comment by balzack** [comment]
thanks for your support...you are awesome!
